sudo: false

language: python

python:
  - 3.5

branches:
  only:
  - master

install:
  - pip install -r requirements.txt

script:
  # Tests
  - python -m unittest discover -v

notifications:
  email:
    recipients:
      - louis.remus@berkeley.edu
      - auriane.blarre@berkeley.edu
    on_success: change
    on_failure: change
